### ISSUE TITLE
suggestion: analyze whether two results are different

### ISSUE THREAD

**Issue by blinsay** [leifwalsh/perfume#3]
it'd be cool to have Perfume do [a k-s test](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.ks_2samp.html) or something similar and report that two benchmarks are/are not significantly different from each other.

**Comment by leifwalsh** [comment]
@blinsay how's this look https://github.com/leifwalsh/perfume/pull/4/files
